# Questions

In [ ]:
marks = 23
name = 'Harsh'

print('Hi',name,"your marks is",marks)
print(f"Hi {name}, your marks is {marks}")

Hi Harsh your marks is 23
Hi Harsh, your marks is 23


#### Q) Find the Volume of a cylinder

In [ ]:
pi = 3.14
r = float(input('Give r '))
h = float(input('Give  '))

vol = (pi*(r**2)*h)
print(f"The Vol of Cylinder is {vol}")

Give r 34
Give  6
The Vol of Cylinder is 21779.04


#### Q) Find Compound Interest

In [ ]:
p = float(input('Give p '))
r = float(input('Give r '))
n = float(input('Give n '))
t = float(input('Give t '))

CI = p * (1+r/n)**(n*t)

print(f'The Compound Interest is {CI}')

Give p 1200
Give r 7
Give n 1
Give t 2
The Compound Interest is 76800.0


In [ ]:
## Comparison Operator

'''
>
<
>=
<=
!=
=
==

'''

a = 10
b = 12

print(a == b)

False


In [ ]:
## Logical Operator

'''
AND
OR
NOT
'''

print((12>b) or (7<=a))

True


# Conditional

In [ ]:
age = 2

if age >= 18:
  print('Eligible')
elif age < 18:
  print('H')
else:
  print('Not Eligible')

H


#### Take age from the user

In [ ]:
# [20-100] - Adult
# [13 - 19] - Teenager
# [0 - 12] - Child
# anything else is invalid age

In [ ]:
age = int(input('Give age '))

if age >= 20 and age <= 100:
  print('Adult')
elif age >= 13:
  print('Teenager')
elif age >= 0:
  print('Child')
else:
  print('Invalid')

Give age 102
Teenager


In [ ]:
if True:
  print('Hi')
  if False:
    print('Hey')
  else:
    print('Hello')
    if False:
      print('Yo')
    else:
      print('H')
  print('A')

Hi
Hello
H


In [ ]:
a = 12
b = 10

if (a>10 or a<12):
  if(b>7 or a<2):
    print('H')
    if(b>2 and a > b):
      print('Hey')
    else:
      print('hi')

H
Hey


#### Q) Check if the number is +ve, if +ve check if it is odd or even else write -ve

In [ ]:
num = int(input('Give n '))

if num > 0:
  print('The num is +ve')
  if num % 2 == 0:
    print('Even')
  else:
    print('Odd')
else:
  print('-ve')

Give n 23
The num is +ve
Odd


#### Q) Check if the number is divisible by 2 and 5 both

In [ ]:
# [Divisible by 2]
# [Divisible by 5]
# [Divisible by both 2 and 5]
# [Divisible by none]

In [ ]:
num = int(input('Give Number '))

if num%2 == 0:
  if num % 5 == 0:
    print('Divisble by both')
  else:
    print('Divisible by 2 and not by 5')

elif num % 5 == 0:
  print('Divisible by 5 not by 2')

else:
  print('Divisible by none')

Give Number 13
Divisible by none


## Check if the number is divisible by 3 and 7

In [ ]:
n = int(input('GIve n '))

if n%3 == 0:
  if n%7 == 0:
    print('Divisible by both')
  else:
    print('Divisible by 3 not 7')
elif n%7 == 0:
  print('Divisible by 7 and not 3')
else:
  print('Divisible by none')

GIve n12
Divisible by 3 not 7


## Report Card Generator

In [ ]:
'''
90 - 100 -A
80 - 89 - B
70 - 79 - C
60 - 69 - D
50 - 59 - E

else F
'''

In [ ]:
name = input('Give Name ')
marks = int(input('Give Marks '))

if marks >= 90 and marks <= 100:
  grade = 'A'
elif marks >= 80 and marks < 90 :
  grade = 'b'
elif marks >= 70 and marks < 80 :
  grade = 'c'
elif marks >= 60 and marks < 70 :
  grade = 'd'
elif marks >= 50 and marks < 60 :
  grade = 'e'
else:
  grade = 'F'

print(f"Hi {name}, your marks are {marks} and your grade is {grade}")

Give Name harsh
Give Marks 88
Hi harsh, your marks are 88 and your grade is b


In [ ]:
name = input('Give Name ')
marks = int(input('Give Marks '))

if marks <= 100:
  if marks >= 90:
    grade = 'A'
  elif marks >= 80:
    grade = 'b'
  elif marks >= 70:
    grade = 'c'
  elif marks >= 60:
    grade = 'd'
  elif marks >= 50:
    grade = 'e'
  else:
    grade = 'F'

print(f"Hi {name}, your marks are {marks} and your grade is {grade}")

Give Name Harsh
Give Marks 120
Invalid Marks
Hi Harsh, your marks are 120 and your grade is c


## Simple Calculator

In [ ]:
num1 = float(input('GIve Num1 '))
num2 = float(input('GIve Num2 '))
operator = input('+,-,*,/')

if operator == "+":
  result = num1 + num2
elif operator == "-":
  result = num1 - num2
elif operator == "*":
  result = num1 * num2
elif operator == "/":
  if num2 == 0:
    print('Invlid OPeration')
  else:
    result = num1 / num2
else:
  print('Invalid OPerator')

print(f"The result is {result}")

GIve Num1 23
GIve Num2 0
+,-,*,//
Invlid OPeration
The result is 540.0


## Login System

In [ ]:
stored_us = 'admin'
stored_pass = 'pass'

u = input('Give username ')
pas = input('GIve Pass')

if u == stored_us:
  if pas == stored_pass:
    print('Login Successful!')
  else:
    print('Invalid Pass')
else:
  print('Invalid Username')

Give username asd
GIve Passfd
Invalid Username


## Employee Bonus Calculator

In [ ]:
name = input('GIve name')
yrs = int(input('Give yrs'))
score = float(input('Give score'))
salary = float(input('GIve salary'))

if score > 4.5 and score < 5:
  if yrs > 10:
    bonus = 20
  elif yrs > 5:
    bonus = 10
  else:
    bonus = 2

elif score >= 3.5 and score < 4.5:
  if yrs > 10:
    bonus = 10
  elif yrs > 5:
    bonus = 5
  else:
    bonus = 0

else:
  bonus = 0

new_salary = salary + (bonus*salary)/100

print(f"Hi {name}, your score is {score} and your new salary is {new_salary}")


GIve nameHarsh
Give yrs11
Give score4.6
GIve salary400000
Hi Harsh, your score is 4.6 and your new salary is 480000.0


# Loops


In [ ]:
i = 1

while i < 6:
  print(i)
  i = i + 1

1
2
3
4
5


## Using a while loop write odd numbers between 1 and 100 and also print the sum of these numbers

In [ ]:
i = 1
sum = 0
while i < 101:
  print(i)
  sum = sum + i
  i = i + 2
print(f"the sum value is {sum}")

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99
the sum value is 2500


In [ ]:
for i in range(1,6):
  print(i)

1
2
3
4
5


In [ ]:
range(5)

range(0, 5)

In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
for i in range(1,5):
  print(i)

1
2
3
4


In [ ]:
for i in range(1,5,2):
  print(i)

1
3


In [ ]:
for i in range(2,7,3):
  print(i)

2
5


In [ ]:
for i in range(5,51,5):
  print(i)

5
10
15
20
25
30
35
40
45
50


In [ ]:
for i in range(5,0,-1):
  print(i)

5
4
3
2
1


In [ ]:
for i in range(50,4,-5):
  print(i)

50
45
40
35
30
25
20
15
10
5


In [ ]:
for i in range(60,5,-6):
  print(i)

60
54
48
42
36
30
24
18
12
6


In [ ]:
## Q)
num = 5

for i in range(num, (num*10)+1,num):
  print(i)

5
10
15
20
25
30
35
40
45
50


In [ ]:
num = 10

for i in range(num*10, num-1, -num):
  print(i)

100
90
80
70
60
50
40
30
20
10


In [ ]:
num = 10
count = 0

for i in range(num, (num*10)+1, num):
  count = count + 1
  print(f"{num} * {count} = {i}")

10 * 1 = 10
10 * 2 = 20
10 * 3 = 30
10 * 4 = 40
10 * 5 = 50
10 * 6 = 60
10 * 7 = 70
10 * 8 = 80
10 * 9 = 90
10 * 10 = 100


In [ ]:
num = 12
count = 11

for i in range(num*10, num-1, -num):
  count = count - 1
  print(f"{num} * {count} = {i}")

10 * 10 = 100
10 * 9 = 90
10 * 8 = 80
10 * 7 = 70
10 * 6 = 60
10 * 5 = 50
10 * 4 = 40
10 * 3 = 30
10 * 2 = 20
10 * 1 = 10


## Q) Find numbers between 1 and 200 that are divisible by both 3 and 7

In [ ]:
for i in range(1,201):
  if (i%3 == 0) and (i%7 == 0):
    print(i)

21
42
63
84
105
126
147
168
189


## Q) Count the  numbers between 1 and 500 that are divisible by 2 3 7 all

In [ ]:
count = 0
for i in range(1,501):
  if (i%2 == 0) and (i%3 == 0) and (i%7 == 0):
    count = count + 1
    count += 1

print(count)

11


## Find the sum of first n natural numbers

In [ ]:
n = 12
sum = 0

for i in range(1,n+1):
  sum = sum + i

print(sum)

78


In [ ]:
for i in range(1,11):
  print(i)
  if i == 5:
    pass

1
2
3
4
5
6
7
8
9
10


## Q) FInd first 10 numbers between 1 and 10000 that are divisible by all 3, 7 and 11

In [ ]:
count = 0

for i in range(1,10001):
  if (i%3 == 0) and (i%7 == 0) and (i%11 == 0):
    count += 1
    print(i)

    if count == 10:
      break


231
462
693
924
1155
1386
1617
1848
2079
2310


In [ ]:
name = 'Harshvardhan Singh'

for i in name:
  print(i, end = " ")

H-a-r-s-h-v-a-r-d-h-a-n- -S-i-n-g-h-

## Q) Find the number of vowels inside the string that the user gives

In [ ]:
string = input('Give a string ')
a = 'aeiouAEIOU'
count = 0

for i in string:
  for j in a:
    if j == i:
      count += 1

print(count)

Give a string aeiou hsjahd safh jkasf hk
8


In [ ]:
string = input('Give a string ')

count = 0

for i in string:
  if (i == 'a') or (i == 'e'):
    count += 1

print(count)

## Q) Find the sum and count of the first 100 odd numbers in the range of 1 and 100000 using for loop

In [ ]:
sum = 0
count = 0

for i in range(1,100001):
  if i % 2 != 0:
    sum = sum + i
    count = count + 1
  if count == 100:
    break

print(f"The sum is {sum} and the count is {count}")

The sum is 10000 and the count is 100


In [ ]:
## Nested Loops

for i in range(1,7):
  for j in range(1,7):
    for k in range(1,7):
      print(i,j,k)
    print('****')

1 1 1
1 1 2
1 1 3
1 1 4
1 1 5
1 1 6
1 2 1
1 2 2
1 2 3
1 2 4
1 2 5
1 2 6
1 3 1
1 3 2
1 3 3
1 3 4
1 3 5
1 3 6
1 4 1
1 4 2
1 4 3
1 4 4
1 4 5
1 4 6
1 5 1
1 5 2
1 5 3
1 5 4
1 5 5
1 5 6
1 6 1
1 6 2
1 6 3
1 6 4
1 6 5
1 6 6
2 1 1
2 1 2
2 1 3
2 1 4
2 1 5
2 1 6
2 2 1
2 2 2
2 2 3
2 2 4
2 2 5
2 2 6
2 3 1
2 3 2
2 3 3
2 3 4
2 3 5
2 3 6
2 4 1
2 4 2
2 4 3
2 4 4
2 4 5
2 4 6
2 5 1
2 5 2
2 5 3
2 5 4
2 5 5
2 5 6
2 6 1
2 6 2
2 6 3
2 6 4
2 6 5
2 6 6
3 1 1
3 1 2
3 1 3
3 1 4
3 1 5
3 1 6
3 2 1
3 2 2
3 2 3
3 2 4
3 2 5
3 2 6
3 3 1
3 3 2
3 3 3
3 3 4
3 3 5
3 3 6
3 4 1
3 4 2
3 4 3
3 4 4
3 4 5
3 4 6
3 5 1
3 5 2
3 5 3
3 5 4
3 5 5
3 5 6
3 6 1
3 6 2
3 6 3
3 6 4
3 6 5
3 6 6
4 1 1
4 1 2
4 1 3
4 1 4
4 1 5
4 1 6
4 2 1
4 2 2
4 2 3
4 2 4
4 2 5
4 2 6
4 3 1
4 3 2
4 3 3
4 3 4
4 3 5
4 3 6
4 4 1
4 4 2
4 4 3
4 4 4
4 4 5
4 4 6
4 5 1
4 5 2
4 5 3
4 5 4
4 5 5
4 5 6
4 6 1
4 6 2
4 6 3
4 6 4
4 6 5
4 6 6
5 1 1
5 1 2
5 1 3
5 1 4
5 1 5
5 1 6
5 2 1
5 2 2
5 2 3
5 2 4
5 2 5
5 2 6
5 3 1
5 3 2
5 3 3
5 3 4
5 3 5
5 3 6
5 4 1
5 4 2
5 4 3
5 4 4
5 4 

## Pattern Printing

In [ ]:
'''

*
**
***
****
*****

'''

In [ ]:
num = 10

for i in range(1,num+1):
  print(i* "* ")

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 
* * * * * * * 
* * * * * * * * 
* * * * * * * * * 
* * * * * * * * * * 


In [ ]:
'''

*****
****
***
**
*

'''

In [ ]:
num = 5

for i in range(num, 0, -1):
  print(i*"* ")

* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
'''

1
22
333
4444
55555

'''

In [ ]:
for i in range(1,6):
  print(str(i)*i)

1
22
333
4444
55555


In [ ]:
'''

*****
*****
*****
*****
*****

'''

In [ ]:
for i in range(1,6):
  print(5 * "*")

*****
*****
*****
*****
*****


In [ ]:
'''

**********
*        *
*        *
*        *
*        *
*        *
*        *
*        *
*        *
**********


'''

In [ ]:
num = 5
print("*"*num)

for i in range(1,num-1):
  print("*"+" "*(num-2)+"*")

print("*"*num)

*****
*   *
*   *
*   *
*****


In [ ]:
'''
*
* *
*  *
*   *
*    *
*     *
********

'''

In [ ]:
print("*")

for i in range(1,7):
  print("*"+" "*i+"*")


print("*"*9)

*
* *
*  *
*   *
*    *
*     *
*      *
*********


In [ ]:
'''

    *
   **
  ***
 ****
*****


'''

In [ ]:
num = 5

for i in range(1,num+1):
  print(' '*(num-i) + "*"*i)

    *
   **
  ***
 ****
*****


In [ ]:
'''

    *
   **
  ***
 ****
*****
*****
 ****
  ***
   **
    *


'''

In [ ]:
num = 5

for i in range(1,num+1):
  print(' '*(num-i) + "*"*i)

for i in range(num, 0, -1):
  print(' '*(num-i) + "*"*i)

    *
   **
  ***
 ****
*****
*****
 ****
  ***
   **
    *


#### Q) Find prime numbers between 1 and 100

In [ ]:
isprime = False

for i in range(2,101):
  isprime = True
  for j in range(2,i):
    if i % j == 0:
      isprime = False
      break
  if isprime:
    print(i)

## Q) Write first 25 prime numbers between 1 and 10000

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


#### Q) Write first 25 prime numbers between 1 and 10000

In [ ]:
isprime = False
count = 0

for i in range(2,10001):
  isprime = True
  for j in range(2,i):
    if i % j == 0:
      isprime = False
      break
  if isprime:
    count = count + 1
    print(i)

  if count == 25:
    break

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


# Data Structures

In [ ]:
'''
name
roll number
class
physics
chem
maths
sections

'''

## List

In [ ]:
lst = []
print(lst)
print(type(lst))

[]
<class 'list'>


In [ ]:
lst = list()
print(type(lst))

<class 'list'>


In [ ]:
lst = [1,2,3,4,5,'Harsh','Amit','vidit',3.14,6.34,77.44,True,False]
print(lst)

[1, 2, 3, 4, 5, 'Harsh', 'Amit', 'vidit', 3.14, 6.34, 77.44, True, False]


In [ ]:
print(lst[-3])

In [ ]:
print(lst[6])

Amit


In [ ]:
print(lst[2])

3


In [ ]:
print(lst[-2])

True


In [ ]:
lst[7] = 'aman'
print(lst)

[1, 2, 3, 4, 5, 'Harsh', 'Amit', 'aman', 3.14, 6.34, 77.44, True, False]


In [ ]:
lst.append(6)
print(lst)

[1, 2, 3, 4, 5, 'Harsh', 'Amit', 'aman', 3.14, 6.34, 77.44, True, False, 'Hey', 6]


#### Q) Create a list with number between 1 and 15 and the numbers should be squared

In [ ]:
lst = []

for i in range(1,16):
  lst.append(i*i)

print(lst)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225]


#### Q) Create a list with numbers between 1 and 5000 and only the even numbers should be present in the list

In [ ]:
lst = []

for i in range(1,5001):
  if i % 2 == 0:
    lst.append(i)

print(lst)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420, 42

In [ ]:
name = ['harsh','aman','vidit','vikas','vaibhav']

#### Q) Find if "Vidit" Exists in this list, if yes print found else print not found

In [ ]:
len(name)

5

In [ ]:
Flag = False

for i in range(len(name)):
  if name[i] == 'vidit':
    Flag = True

if Flag:
  print('Found')
else:
  print('NOt Found')

Found


In [ ]:
name = ['harsh','aman','vidit','vikas','vaibhav']

In [ ]:
print(name[1:2:2])

['aman']


In [ ]:
## List Slicing

print(name[::-2])

['vaibhav', 'vidit', 'harsh']


In [ ]:
name = ['harsh','aman','vidit','vikas','vaibhav']

In [ ]:
name.append('Hey')
print(name)

['harsh', 'aman', 'vidit', 'vikas', 'vaibhav', 'Hey']


In [ ]:
name.insert(1,'Hello')
print(name)

['harsh', 'Hello', 'aman', 'vidit', 'vikas', 'vaibhav', 'Hey']


In [ ]:
name.remove('Hey')
print(name)

['harsh', 'Hello', 'aman', 'vidit', 'vikas', 'vaibhav']


In [ ]:
popped_element = name.pop()
print(popped_element)
print(name)

IndexError: pop from empty list

List Comprehension

* Basics Syantax [expression for item in iterable]

* with conditional logic [expression for item in iterable if condition]

* Nested List Comprehension [expression for item1 in iterable1 for item2 in iterable2]


In [ ]:
lst = []

for i in range(1,11):
  lst.append(i*i)

print(lst)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
[i*i for i in range(1,11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
lst = []

for i in range(1,51):
  if i % 2 == 0:
    lst.append(i)

print(lst)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


In [ ]:
print([i for i in range(1,51) if i % 2 == 0])

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


In [ ]:
lst = []

for i in range(1,7):
  for j in range(1,7):
    lst.append((i,j))

print(lst)

[(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6)]


In [ ]:
print([(i,j) for i in range(1,7) for j in range(1,7)])

[(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6)]


In [ ]:
lst = [1,2,3,4,[3,4,5]]
print(lst[4][2])

5


In [ ]:
lst = [1,2,3,[2,3,4,[6,7,8],[7,8,9],[3,4,6,[11]]]]

In [ ]:
lst[3][5][3][0]

11

In [ ]:
lst = [[1,2,3,4,5],
       [5,6,7,3,5],
       [5,6,8,4,2],
       [7,9,6,3,5],
       [3,5,7,8,9]]

In [ ]:
(0,4) (1,3) (2,2)

27


In [ ]:
sum = 0

for i in range(len(lst)):
  for j in range(len(lst)):
    if i == j:
      sum = sum + lst[i][j]

print(sum)

27


In [ ]:
sum = 0

for i in range(len(lst)):
  for j in range(len(lst)):
    if i + j == len(lst) - 1:
      sum = sum + lst[i][j]

print(sum)

28


In [ ]:
subject = ['English','Maths','Physics','Chem','Bio']
marks = [45,76,23,68,97]
sum = 0

for i in range(0,len(marks)):
  sum = sum + marks[i]

avg = sum / len(marks)
print(avg)

61.8


In [ ]:
'''
GRADES

90 - 100 -> A
80 - 90 -> B
..

..
anything less than 40 is FAIL
'''

In [ ]:
'''
ENGLISH 45 B

'''

In [ ]:
subject = ['English','Maths','Physics','Chem','Bio']
marks = [45,76,23,68,97]

In [ ]:
'''
English 45 PASS
MATHS 76 PASS

'''

In [ ]:
for i in range(len(marks)):
  if marks[i] > 33:
    print(f"{subject[i]} {marks[i]} PASS")
  else:
    print(f"{subject[i]} {marks[i]} FAIL")

English 45 PASS
Maths 76 PASS
Physics 23 FAIL
Chem 68 PASS
Bio 97 PASS


In [ ]:
'''
GRADES

90 - 100 -> A
80 - 90 -> B
..

..
anything less than 40 is FAIL
'''

In [ ]:
for i in range(len(marks)):
  if 100 >= marks[i] >= 90:
    print(f"{subject[i]} {marks[i]} A")
  elif 90 > marks[i] > 80:
    print(f"{subject[i]} {marks[i]} B")
  elif 80 > marks[i] > 70:
    print(f"{subject[i]} {marks[i]} c")
  elif 70 > marks[i] > 60:
    print(f"{subject[i]} {marks[i]} d")
  else:
    print(f"{subject[i]} {marks[i]} FAIL")

English 45 FAIL
Maths 76 c
Physics 23 FAIL
Chem 68 d
Bio 97 A


# Tuple

In [ ]:
tup = ()
print(tup)
print(type(tup))

()
<class 'tuple'>


In [ ]:
tup = (1,2,3,4,"Asd","dlis",3.23,5.75,75.53,True,False)
print(tup)

(1, 2, 3, 4, 'Asd', 'dlis', 3.23, 5.75, 75.53, True, False)


In [ ]:
print(tup[2])

3


In [ ]:
tup = list(tup)

In [ ]:
tup[4] = 12
print(tup)

[1, 2, 3, 4, 12, 'dlis', 3.23, 5.75, 75.53, True, False]


In [ ]:
tup = tuple(tup)

In [ ]:
tup = 1,34,'Harsh',56.54
print(tup)
print(type(tup))

(1, 34, 'Harsh', 56.54)
<class 'tuple'>


In [ ]:
tup = (1,2,3)

In [ ]:
a,b,c = tup
print(a)
print(b)
print(c)

1
2
3


In [ ]:
tup = (1,2,3,4,'hatsh','Trds',True)

a,*b,c = tup
print(a)
print(b)
print(c)

1
[2, 3, 4, 'hatsh', 'Trds']
True


# Set

In [ ]:
se = {1}
print(se)
print(type(se))

{1}
<class 'set'>


In [ ]:
s = {1,23,45,67,23,6,'Harsh',1,1,1,1,1,1}
print(s)

{1, 67, 6, 23, 'Harsh', 45}


In [ ]:
st = 'Hey thi is sdh sfk'
print(st.split())

['Hey', 'thi', 'is', 'sdh', 'sfk']


#### Find Unique Words in this

In [ ]:
s = 'This is a classroom of Python and we are learning Python today in this classroom'

a = s.split()
a = set(a)
print(a)
print(len(a))

{'classroom', 'This', 'of', 'today', 'Python', 'we', 'learning', 'and', 'are', 'in', 'this', 'a', 'is'}
13


In [ ]:
lst = [1,2,3,(2,3,45),[5,6,7,8],(23,[6,7,8],{2,4,56})]
print(lst)
print(type(lst))

[1, 2, 3, (2, 3, 45), [5, 6, 7, 8], (23, [6, 7, 8], {56, 2, 4})]
<class 'list'>


In [ ]:
tip = (1,2,[2,4,6,6],[3,5,6])
print(tip)
print(type(tip))

(1, 2, [2, 4, 6, 6], [3, 5, 6])
<class 'tuple'>


In [ ]:
set1 = {2,3,5,7}
set2 = {6,8,3,2,4,5}

# print(set1.union(set2))
# print(set2.difference(set1))
# print(set2.intersection(set1))

{2, 3, 5}


# Dictionary

In [ ]:
dic = dict()
print(dic)
print(type(dic))

{}
<class 'dict'>


In [ ]:
dic = {1:'Harsh',2:'ABC',3:'CDE',1:'Amit'}
print(dic)

{1: 'Amit', 2: 'ABC', 3: 'CDE'}


In [ ]:
dic[4] = 'Divij'
print(dic)

{1: 'Amit', 2: 'ABC', 3: 'CDE', 4: 'Divij'}


In [ ]:
dic['ABC'] = 12
print(dic)

{1: 'Amit', 2: 'ABC', 3: 'CDE', 4: 'Divij', 'ABC': 12}


In [ ]:
print(dic.keys())
print(dic.values())
print(dic.items())

dict_keys([1, 2, 3, 4, 'ABC'])
dict_values(['Amit', 'ABC', 'CDE', 'Divij', 12])
dict_items([(1, 'Amit'), (2, 'ABC'), (3, 'CDE'), (4, 'Divij'), ('ABC', 12)])


In [ ]:
print(dic)

{1: 'Amit', 2: 'ABC', 3: 'CDE', 4: 'Divij', 'ABC': 12}


In [ ]:
print(dic['ABC'])

12


In [ ]:
print(dic.get('Amit','Invalid'))

Invalid


In [ ]:
dic

{1: 'Amit', 2: 'ABC', 3: 'CDE', 4: 'Divij', 'ABC': 12}

In [ ]:
dic_copy = dic
print(dic_copy)
print(dic)

{1: 'Amit', 2: 'ABC', 3: 'CDE', 4: 'Divij', 'ABC': 12}
{1: 'Amit', 2: 'ABC', 3: 'CDE', 4: 'Divij', 'ABC': 12}


In [ ]:
dic[5] = 'Vikas'
print(dic)

{1: 'Amit', 2: 'ABC', 3: 'CDE', 4: 'Divij', 'ABC': 12, 5: 'Vikas'}


In [ ]:
print(dic_copy)

{1: 'Amit', 2: 'ABC', 3: 'CDE', 4: 'Divij', 'ABC': 12, 5: 'Vikas'}


In [ ]:
dic_copy1 = dic.copy()

In [ ]:
print(dic_copy1)
print(dic)

{1: 'Amit', 2: 'ABC', 3: 'CDE', 4: 'Divij', 'ABC': 12, 5: 'Vikas'}
{1: 'Amit', 2: 'ABC', 3: 'CDE', 4: 'Divij', 'ABC': 12, 5: 'Vikas'}


In [ ]:
dic[7] = 'AAA'
print(dic)
print(dic_copy1)

{1: 'Amit', 2: 'ABC', 3: 'CDE', 4: 'Divij', 'ABC': 12, 5: 'Vikas', 7: 'AAA'}
{1: 'Amit', 2: 'ABC', 3: 'CDE', 4: 'Divij', 'ABC': 12, 5: 'Vikas'}


In [ ]:
dic

{1: 'Amit', 2: 'ABC', 3: 'CDE', 4: 'Divij', 'ABC': 12, 5: 'Vikas', 7: 'AAA'}

In [ ]:
for i in dic.keys():
  print(i)

1
2
3
4
ABC
5
7


In [ ]:
for  i in dic.values():
  print(i)

Amit
ABC
CDE
Divij
12
Vikas
AAA


In [ ]:
for i in dic.keys():
  print(f"{i} {dic[i]}")

1 Amit
2 ABC
3 CDE
4 Divij
ABC 12
5 Vikas
7 AAA


In [ ]:
for i,j in dic.items():
  if j == 'Vikas':
    print(i,j)

5 Vikas


In [ ]:
d = {
    'Class_1':['Harsh','Amit','Chinmoy'],
    'Marks':[23,56,34]
}

In [ ]:
d

{'Class_1': ['Harsh', 'Amit', 'Chinmoy'], 'Marks': [23, 56, 34]}

In [ ]:
d['Class_1']

['Harsh', 'Amit', 'Chinmoy']

In [ ]:
d = {
    123:{'name':'Harsh','age':26,'country':'India'},
    124:{'name':'ABC','age':27,'country':'India'}
}

In [ ]:
d

{123: {'name': 'Harsh', 'age': 26, 'country': 'India'},
 124: {'name': 'ABC', 'age': 27, 'country': 'India'}}

In [ ]:
for i,j in d.items():
  for l,m in j.items():
    print(l,m)

name Harsh
age 26
country India
name ABC
age 27
country India


In [ ]:
students = {
    "S001": {
        "name": "Alice Johnson",
        "age": 17,
        "section": "A",
        "roll_no": 1,
        "marks": {
            "Mathematics": 88,
            "Physics": 92,
            "Chemistry": 85
        }
    },
    "S002": {
        "name": "Rahul Kumar",
        "age": 18,
        "section": "B",
        "roll_no": 2,
        "marks": {
            "Mathematics": 79,
            "Physics": 81,
            "Chemistry": 78
        }
    },
    "S003": {
        "name": "Sneha Patel",
        "age": 17,
        "section": "A",
        "roll_no": 3,
        "marks": {
            "Mathematics": 95,
            "Physics": 89,
            "Chemistry": 94
        }
    },
    "S004": {
        "name": "Mohammed Farhan",
        "age": 18,
        "section": "C",
        "roll_no": 4,
        "marks": {
            "Mathematics": 72,
            "Physics": 76,
            "Chemistry": 70
        }
    },
    "S005": {
        "name": "Priya Singh",
        "age": 17,
        "section": "B",
        "roll_no": 5,
        "marks": {
            "Mathematics": 83,
            "Physics": 88,
            "Chemistry": 90
        }
    }
}


In [ ]:
for i,j in students.items():
  # print(i,j)
  print('Name    :',j['name'])
  print('Age     : ',j['age'])
  print('Section :',j['section'])
  print('Roll No :',j['roll_no'])
  print("*" * 25)

Name    : Alice Johnson
Age     :  17
Section : A
Roll No : 1
*************************
Name    : Rahul Kumar
Age     :  18
Section : B
Roll No : 2
*************************
Name    : Sneha Patel
Age     :  17
Section : A
Roll No : 3
*************************
Name    : Mohammed Farhan
Age     :  18
Section : C
Roll No : 4
*************************
Name    : Priya Singh
Age     :  17
Section : B
Roll No : 5
*************************


In [ ]:
'''

Name :
Age  :
Section :
Roll_No :
AVG Marks:

*************

Name :
Age  :
Section :
Roll_No :
AVG Marks:

**************

Name :
Age  :
Section :
Roll_No :
AVG Marks:


'''

In [ ]:
## Q) Using dictionary find the occurance of each element in this list

lst = [1,1,1,2,2,3,3,3,3,4,4,4,5,5,5]
freq = {}

In [ ]:
for i in lst:
  if i in freq:
    freq[i] += 1
  else:
    freq[i] = 1

print(freq)

{1: 3, 2: 2, 3: 4, 4: 3, 5: 3}


In [ ]:
{1:3,2:2,3:4,4:3,5:3}

# Numpy

In [ ]:
import streamlit

In [ ]:
!pip install streamlit

In [ ]:
import numpy as np

In [ ]:
# lst = [1,2,3,4,5]
# print(type(lst))

arr = np.array(lst,ndmin = 4)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[[[1 2 3 4 5]]]]


In [ ]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin = 3)

arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])

print('Total : ', arr.size)
print('Rows  : ', np.size(arr,0))
print('Cols  : ', np.size(arr,1))

arr

Total :  12
Rows  :  4
Cols  :  3


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
arr.shape

(4, 3)

In [ ]:
arr = np.ones(shape = (3,5), dtype = int)

print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
np.eye(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
np.random.rand(3,4)

array([[0.28555696, 0.62540625, 0.99784109, 0.65351931],
       [0.80185321, 0.11857447, 0.74186818, 0.57763913],
       [0.08386994, 0.62842936, 0.7508591 , 0.32397435]])

In [ ]:
np.random.randint(low = 1, high = 10, size = 10)

array([3, 8, 8, 8, 2, 5, 2, 8, 4, 7])

In [ ]:
import numpy as np

In [ ]:
import matplotlib.pyplot as plt

plt.hist(np.random.randn(10000000), bins = 10000000);

KeyboardInterrupt: 

Error in callback <function _draw_all_if_interactive at 0x7985dc8abec0> (for post_execute):


KeyboardInterrupt: 

Error in callback <function flush_figures at 0x7985dc8a9800> (for post_execute):


KeyboardInterrupt: 

In [ ]:
git clone "https://github.com/HarshvardhanSingh-13/Datasets"

SyntaxError: invalid syntax (<ipython-input-1-4247074606>, line 1)

In [ ]:
!git clone "https://github.com/HarshvardhanSingh-13/Datasets"

Cloning into 'Datasets'...
remote: Enumerating objects: 287, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 287 (delta 10), reused 0 (delta 0), pack-reused 242 (from 1)
Receiving objects: 100% (287/287), 301.25 MiB | 33.91 MiB/s, done.
Resolving deltas: 100% (124/124), done.
Updating files: 100% (231/231), done.


In [ ]:
import numpy as np

In [ ]:
arr = np.zeros(shape = (8,8), dtype = int)

print(arr)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [ ]:
for i in range(np.size(arr,0)):
  for j in range(np.size(arr,0)):
    if (i + j)%2 == 0:
      arr[i][j] = 1

print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
import pandas as pd

In [ ]:
lst = [1,2,3,4,5]

pd.Series(lst)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
pd.Series(index = ['Eshant', 'Pranjal', 'Jayesh', 'Ashish'], data = [1,2,3,4])

Eshant     1
Pranjal    2
Jayesh     3
Ashish     4
dtype: int64

In [ ]:
steps = {'day1' : 4000, 'day2' : 3000, 'day3' : 12000}

pd.Series(steps)

day1     4000
day2     3000
day3    12000
dtype: int64

In [ ]:
lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks']

pd.DataFrame(lst)

0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [ ]:
lst = [['tom',10],['jerry',12],['spike',14]]

pd.DataFrame(lst)

0   1
0    tom  10
1  jerry  12
2  spike  14

In [ ]:
data = { 'Name'         :['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age'          :[27, 24, 22, 32],
         'Address'      :['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
         'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

df = pd.DataFrame(data)

df

Name  Age    Address Qualification
0     Jai   27      Delhi           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannauj           Phd

In [ ]:
df = pd.read_csv('/content/Datasets/Airbnb/airbnb_v2.csv')

In [ ]:
df

Unnamed: 0        id  \
0               0  49849504   
1               1  50891766   
2               2  50699164   
3               3  49871422   
4               4  51245886   
...           ...       ...   
12800       12800  44697740   
12801       12801  29975283   
12802       12802  32977697   
12803       12803   8006146   
12804       12804  40547903   

                                                    name rating reviews  \
0                                         Perla bungalov   4.71      64   
1      Authentic Beach Architect Sheltered Villa with...    New       0   
2                                      cottages sataplia   4.85      68   
3                            Sapanca Breathable Bungalow    5.0      13   
4                                          Bungalov Ev 2    New       0   
...                                                  ...    ...     ...   
12800            Brown Dome House No. 3, full of healing   4.94      16   
12801       Bubble Hotel Ubud with Bathtub under the Sky   4.67       6   
12802                                   Paradise Eco Hub   4.67       3   
12803     WisDOME - Mentigi Bay Village - Gilis - Lombok   4.86       7   
12804   Enjoy Vitamin SEA!  Ocean Front! [Ocean's Seven]   4.85      13   

         host_name      host_id  \
0        Mehmetcan  357334205.0   
1            Fatih  386223873.0   
2           Giorgi  409690853.0   
3            Melih  401873242.0   
4      Arp Sapanca  414884116.0   
...            ...          ...   
12800        Aidan  161552316.0   
12801       Martha  118954227.0   
12802        Silas  175214568.0   
12803      Cempaka     718423.0   
12804         Achy  246470880.0   

                                                 address  \
0                               Kartepe, Kocaeli, Turkey   
1                                   Kaş, Antalya, Turkey   
2                                       Imereti, Georgia   
3                               Sapanca, Sakarya, Turkey   
4                               Sapanca, Sakarya, Turkey   
...                                                  ...   
12800  Imhoe-myeon, Jindo, South Jeolla Province, Sou...   
12801                                 Gianyar, Indonesia   
12802                                     Kabale, Uganda   
12803        Gunung Sari, Nusa Tenggara Barat, Indonesia   
12804                              Uruma, Okinawa, Japan   

                                           features  \
0              2 guests,2 bedrooms,1 bed,1 bathroom   
1            4 guests,2 bedrooms,2 beds,2 bathrooms   
2              4 guests,1 bedroom,3 beds,1 bathroom   
3              4 guests,1 bedroom,2 beds,1 bathroom   
4               2 guests,1 bedroom,1 bed,1 bathroom   
...                                             ...   
12800                          4 guests,8 bathrooms   
12801     2 guests,1 bedroom,1 bed,Toilet with sink   
12802  2 guests,1 bedroom,2 beds,1 private bathroom   
12803      8 guests,2 bedrooms,4 beds,2.5 bathrooms   
12804          5 guests,1 bedroom,2 beds,1 bathroom   

                                               amenities  ...  price  \
0      Mountain view,Valley view,Lake access,Kitchen,...  ...   8078   
1      Kitchen,Wifi,Dedicated workspace,Free parking ...  ...   4665   
2      Mountain view,Kitchen,Wifi,Dedicated workspace...  ...   5991   
3      Mountain view,Valley view,Kitchen,Wifi,Free pa...  ...  11339   
4      Kitchen,Wifi,Free parking on premises,TV,Air c...  ...   6673   
...                                                  ...  ...    ...   
12800  Kitchen,Wifi,Free parking on premises,Private ...  ...   4288   
12801  Wifi,Free on-street parking,Air conditioning,G...  ...  15200   
12802  Wifi,Breakfast,Long-term stays allowed,Unavail...  ...   9103   
12803  Kitchen,Wifi,Dedicated workspace,Free parking ...  ...  42262   
12804  Sea view,Beach access – Beachfront,Kitchen,Wif...  ...   9909   

            country bathrooms  beds guests  toiles  bedrooms  stu